% defines anything that is measurable, measurables can be combined with
% trackers to generate simulation data
classdef Measurable < DeepCopyable
    properties
        Dimension
    end
    methods (Abstract)
        % this function has to return in a format, where the i-th index
        % refers to the measuremet of the i-th parallel run
        data = measure(this, simulation);
        % formats passed data generated by this measurable, such that each 
        % row corresponds to the results of a single run
        data = format(this, data);
        data = unformat(this, data); % undos a format
        % create the plotter to be used to visualize this measurable
        plt = createPlotter(this, simulation);
    end    
    methods
        % a routine to setup measurements depending on the simulation
        function this = initialize(this, tracker, simulation)
            this.Dimension = simulation.Model.D;
        end
        % use this routine if a measurement depends on more than the
        % current state of the simulation. this will be called on every
        % simulation step, even before calling measure, if measure is to be
        % called in that step.
        function this = onTick(this, simulation)
        end        
        function name = getName(this)
            name = class(this);
        end
    end
end

